force-app/main/default/objects/Saved_Request__c/Saved_Request__c.object-meta.xml
<CustomObject>
    <description>To store the request set</description>
    <label>Saved Request</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Saved Requests Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Request__c/fields/Asynchronous_Run__c.field-meta.xml
<CustomField>
    <fullName>Asynchronous_Run__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checking this box will make an asynchrounous api request depending on the scheduler configuration at a specified time.</description>
    <inlineHelpText>Check this box to include the api request in the Asynchronous run.</inlineHelpText>
    <label>Asynchronous Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Header_Information__c.field-meta.xml
<CustomField>
    <fullName>Header_Information__c</fullName>
    <label>Header Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Method_Type__c.field-meta.xml
<CustomField>
    <fullName>Method_Type__c</fullName>
    <label>Method Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Query_Paramters__c.field-meta.xml
<CustomField>
    <fullName>Query_Paramters__c</fullName>
    <label>Query Paramters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Request_Name__c</fullName>
    <description>Holds unique Name of the request</description>
    <externalId>true</externalId>
    <label>Request Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CalloutSchedulerTest.cls
@istest
public class CalloutSchedulerTest {
	private class RestMock implements HttpCalloutMock {

        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = '{"id":"0015j00000YUEutAAH","success":true,"errors":[]}';

            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }

    @istest()
    public static void testPost(){
        
        //setting up mock
        Test.setMock(HttpCalloutMock.class, new RestMock());
        
        //setting up requestWrapper
        Saved_Request__c SR = new Saved_Request__c();
        SR.Method_Type__c = 'POST';
        SR.URL__c = 'https://resourceful-raccoon-cbu6w8-dev-ed.my.salesforce.com/services/data/v42.0/sObject/Account';
        SR.Request_Payload__c = '{ "name": "Test Name" }';
        SR.Header_Information__c = '[{"id":0,"type":"headerInformation","key":"Authorization","value":"Bearer 00D5j000005Kq43!ARIAQOwWZmEqPgLvnKyyXWCIDt9.gi78bqghhAn41DSZCmriwstTreV1KMlEAjE_OyvR2IiDePNfkAD.m3OidZ2Ig9RmNfas","shouldInclude":true},{"id":1,"type":"headerInformation","key":"Content-Type","value":"application/json;charset=UTF-8","shouldInclude":true}]';
        SR.Query_Paramters__c = '[{"id":0,"type":"queryParameter","key":"","value":"","shouldInclude":false}]';                                 
		SR.Request_Name__c = 'Test  Request';
        SR.Asynchronous_Run__c = true;
        
        insert SR;
        
        Test.startTest();
        CalloutScheduler CS = new CalloutScheduler();
        String sch ='0 48 * * * ?'; 
        System.schedule('Schedule to make api requests', sch,CS);
        Test.stopTest();
		        
    }
}