force-app/main/default/objects/Saved_Request__c/Saved_Request__c.object-meta.xml
<CustomObject>
    <description>To store the request set</description>
    <label>Saved Request</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Saved Requests Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Request__c/fields/Asynchronous_Run__c.field-meta.xml
<CustomField>
    <fullName>Asynchronous_Run__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checking this box will make an asynchrounous api request depending on the scheduler configuration at a specified time.</description>
    <inlineHelpText>Check this box to include the api request in the Asynchronous run.</inlineHelpText>
    <label>Asynchronous Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Header_Information__c.field-meta.xml
<CustomField>
    <fullName>Header_Information__c</fullName>
    <label>Header Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Method_Type__c.field-meta.xml
<CustomField>
    <fullName>Method_Type__c</fullName>
    <label>Method Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Query_Paramters__c.field-meta.xml
<CustomField>
    <fullName>Query_Paramters__c</fullName>
    <label>Query Paramters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Request_Name__c</fullName>
    <description>Holds unique Name of the request</description>
    <externalId>true</externalId>
    <label>Request Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CalloutBatch.cls
public class CalloutBatch implements Database.Batchable<sObject>,Database.AllowsCallouts{
 
    public static string query;
    public CalloutBatch(){
    }
 
    public Database.QueryLocator start(Database.BatchableContext BC){
        query = 'select Query_Paramters__c,Header_Information__c,Request_Name__c,Request_Payload__c,Method_Type__c,URL__c,Name,id from Saved_Request__c where Asynchronous_Run__c=true';
        system.debug('query '+query);
       return Database.getQueryLocator(query);
    }
 
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        List<RestRequestController.RequestResponseWrapper> RequestResponseWrapperList = new List<RestRequestController.RequestResponseWrapper>();
        for(sobject obj : scope){
            RestRequestController.RequestResponseWrapper reqResWrapper = makeCallout(obj);
            RequestResponseWrapperList.add(reqResWrapper);
        }

        //to log transaction
        RestRequestController.logBulkAPITransactions(RequestResponseWrapperList);
    }
 
    public void finish(Database.BatchableContext BC){
    }

    public RestRequestController.RequestResponseWrapper makeCallout(sObject obj){
        Saved_Request__c SR = (Saved_Request__c)obj;

        //preparing request wrapper
        RestRequestController.RequestInformationWrapper reqInfoWrapper = new RestRequestController.RequestInformationWrapper();
        reqInfoWrapper.headerInformationList = (List<object>)JSON.deserializeUntyped(SR.Header_Information__c);
        reqInfoWrapper.queryParameters = (List<object>)JSON.deserializeUntyped(SR.Query_Paramters__c);
        reqInfoWrapper.requestString = SR.Request_Payload__c;
        reqInfoWrapper.url = SR.URL__c;
        reqInfoWrapper.methodType = SR.Method_Type__c;

        //parent information for logging
        RestRequestController.SavedRequestWrapper saReqWrapper = new RestRequestController.SavedRequestWrapper();
        saReqWrapper.requestName = SR.Request_Name__c;
        saReqWrapper.requestId = SR.id;
        saReqWrapper.transactionOrigin = 'Scheduled - Asynchronous';

        //making callout
        RestRequestController.ResponseWrapper resWrapper = RestRequestController.makeRestRequest(reqInfoWrapper);

        return new RestRequestController.RequestResponseWrapper(reqInfoWrapper,resWrapper,saReqWrapper);
        
    }
 }