force-app/main/default/objects/Saved_Request__c/Saved_Request__c.object-meta.xml
<CustomObject>
    <description>To store the request set</description>
    <label>Saved Request</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Saved Requests Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Request__c/fields/Header_Information__c.field-meta.xml
<CustomField>
    <fullName>Header_Information__c</fullName>
    <label>Header Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Method_Type__c.field-meta.xml
<CustomField>
    <fullName>Method_Type__c</fullName>
    <label>Method Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Query_Paramters__c.field-meta.xml
<CustomField>
    <fullName>Query_Paramters__c</fullName>
    <label>Query Paramters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Request_Name__c</fullName>
    <description>Holds unique Name of the request</description>
    <externalId>true</externalId>
    <label>Request Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SavedRequestsController.cls
public with sharing class SavedRequestsController {

    @AuraEnabled(cacheable=true)
    public static List<Saved_Request__c> getSavedRequests(string searchKey) {
        List<Saved_Request__c> requestList;
        try {
            String queryString = 'select Query_Paramters__c,Header_Information__c,Request_Name__c,Request_Payload__c,Method_Type__c,URL__c,Name,id from Saved_Request__c';
            if(String.isNotblank(searchKey)){
                string tempInput = '\'%' + searchKey + '%\'';
                queryString = queryString + ' where Request_Name__c Like '+tempInput;
            }
            queryString = queryString + ' order by lastmodifieddate desc limit 9';
            requestList= database.query(queryString);
            
        } catch (Exception e) {
            System.debug('line and error '+e.getLineNumber() +' '+e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
        return requestList;
    }
}