force-app/main/default/objects/Outbound_log__c/Outbound_log__c.object-meta.xml
<CustomObject>
    <label>Outbound log</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Outbound log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outbound_log__c/fields/Header_Information__c.field-meta.xml
<CustomField>
    <fullName>Header_Information__c</fullName>
    <description>In serialised form</description>
    <label>Header Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Outbound_log__c/fields/Method_Type__c.field-meta.xml
<CustomField>
    <fullName>Method_Type__c</fullName>
    <label>Method Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outbound_log__c/fields/Query_Paramters__c.field-meta.xml
<CustomField>
    <fullName>Query_Paramters__c</fullName>
    <description>In serialised form</description>
    <label>Query Paramters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Outbound_log__c/fields/Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Request_Name__c</fullName>
    <label>Request Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outbound_log__c/fields/Response_status_code__c.field-meta.xml
<CustomField>
    <fullName>Response_status_code__c</fullName>
    <label>Response status code</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outbound_log__c/fields/Saved_Request__c.field-meta.xml
<CustomField>
    <fullName>Saved_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the request the transaction was made from.</description>
    <label>Saved Request</label>
    <referenceTo>Saved_Request__c</referenceTo>
    <relationshipName>Real_Time_Outbound_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outbound_log__c/fields/Time_Elapsed__c.field-meta.xml
<CustomField>
    <fullName>Time_Elapsed__c</fullName>
    <inlineHelpText>In Seconds</inlineHelpText>
    <label>Time Elapsed</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outbound_log__c/fields/Transaction_Origin__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Origin__c</fullName>
    <description>This field determines whether the transaction was logged from the UI by an end user or automatically logged after a scheduled job makes a periodic request to target.</description>
    <label>Transaction Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled - Asynchronous</fullName>
            </value>
            <value>
                <fullName>UI - Synchronous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Request__c/Saved_Request__c.object-meta.xml
<CustomObject>
    <description>To store the request set</description>
    <label>Saved Request</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Saved Requests Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Request__c/fields/Header_Information__c.field-meta.xml
<CustomField>
    <fullName>Header_Information__c</fullName>
    <label>Header Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Method_Type__c.field-meta.xml
<CustomField>
    <fullName>Method_Type__c</fullName>
    <label>Method Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Query_Paramters__c.field-meta.xml
<CustomField>
    <fullName>Query_Paramters__c</fullName>
    <label>Query Paramters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Saved_Request__c/fields/Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Request_Name__c</fullName>
    <description>Holds unique Name of the request</description>
    <externalId>true</externalId>
    <label>Request Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RestRequestController.cls
/**
 * @description       : 
 * @author            : Karthik 
 * @group             : 
 * @last modified on  : 03-21-2024
 * @last modified by  : Karthik 
**/
public with sharing class RestRequestController {
    public static Long startTime;
    public static Long stoptTime;
    public static Decimal timeElapsedForApexError;

    
    @AuraEnabled()
    public static ResponseWrapper makeRestRequest(RestRequestController.RequestInformationWrapper requestWrapper){
        try {
            startTime = DateTime.now().getTime();
            System.debug('requestWrapper '+requestWrapper);
            if(Label.skipRemoteProxyCheckAndCreation != 'yes')    //skips the remote site check and creation if the custom label is set to yes
                MetadataAPIUtility.handlePrerequisitesForCallout(requestWrapper);
            Httpresponse response = OutBoundIntegration.handleOutboundCall(requestWrapper);
            System.debug('response code '+ response.getStatusCode());
            System.debug('Response '+response);

            return new ResponseWrapper(response);
        } catch (Exception e) {
            System.debug('makeRestRequest message'+e.getMessage());
            System.debug('exception line '+e.getLineNumber());
            return apexError(e);
        }
    }

    @AuraEnabled()
    public static void logAPITransaction(ResponseWrapper resWraper,RestRequestController.RequestInformationWrapper requestWrapper,RestRequestController.SavedRequestWrapper savedReqwrapper){
        try {
            system.debug('resWraper '+resWraper);
            system.debug('requestWrapper '+requestWrapper);
            Outbound_log__c rto= prepareOutboundLogObject(resWraper,requestWrapper,savedReqwrapper);
            insert rto;
        } catch (Exception e) {
            throw e;
        }
    }

    public static void logBulkAPITransactions(List<RestRequestController.RequestResponseWrapper> RequestResponseWrapperList)
    {
        try {
            List<Outbound_log__c> realTimeOutboundLogList = new List<Outbound_log__c>();
            for(RestRequestController.RequestResponseWrapper reqResWrapper :RequestResponseWrapperList){
                Outbound_log__c rto= prepareOutboundLogObject(reqResWrapper.resWrapper,reqResWrapper.reqInfoWrapper,reqResWrapper.saReqWrapper);
                realTimeOutboundLogList.add(rto);
            }
            if(!realTimeOutboundLogList.isEmpty()){
                insert realTimeOutboundLogList;
            }
        } catch (Exception e) {
            throw e;
        }
    }
    
    public static Outbound_log__c prepareOutboundLogObject(RestRequestController.ResponseWrapper resWraper,RestRequestController.RequestInformationWrapper requestWrapper,RestRequestController.SavedRequestWrapper savedReqwrapper) {
        try {
            Outbound_log__c rto = new Outbound_log__c();
            rto.URL__c	 = requestWrapper.url;
            rto.Header_Information__c = JSON.serialize(requestWrapper.headerInformationList);
            rto.Query_Paramters__c	 = JSON.serialize(requestWrapper.queryParameters);
            rto.Method_Type__c = requestWrapper.methodType;
            rto.Request__c = requestWrapper.requestString;
            rto.Response__c = resWraper.responseBody;
            rto.Response_status_code__c	 = resWraper.statusCode;
            rto.Time_Elapsed__c	= resWraper.timeElapsed;
            rto.Request_Name__c	= savedReqwrapper.requestName;
            system.debug('savedReqwrapper.requestId '+savedReqwrapper.requestId);
            if(String.isNotBlank(savedReqwrapper.requestId)){
                rto.Saved_Request__c = savedReqwrapper.requestId;
            }
            system.debug('savedReqwrapper.transactionOrigin '+savedReqwrapper.transactionOrigin);
            rto.Transaction_Origin__c = savedReqwrapper.transactionOrigin;
            return rto;
            
        } catch (Exception e) {
            System.debug(e.getMessage());
            System.debug('Exception method : prepareOutboundLogObject');
            System.debug('exception line '+e.getLineNumber());
            throw e;
        }
        
    }



    public static ResponseWrapper apexError(Exception e){
        Map<string,string> errorResponseForApexError = new map<string,string>();
        errorResponseForApexError.put('Message',e.getMessage());
        stoptTime = DateTime.now().getTime();
        timeElapsedForApexError = (stoptTime-startTime)/1000;
        ResponseWrapper rw = new ResponseWrapper();
        rw.statusCode = 400;
        rw.responseBody =  JSON.serialize(errorResponseForApexError);
        rw.status =  'ERROR';
        rw.timeElapsed =  timeElapsedForApexError;
        return rw;
    }

    public class RequestInformationWrapper{
        @AuraEnabled 
        public String methodType {get; set;}
        @AuraEnabled 
        public String url {get; set;}
        @AuraEnabled 
        public String requestString {get; set;}
        @AuraEnabled 
        public List<object> queryParameters {get; set;}
        @AuraEnabled 
        public List<object> headerInformationList {get; set;}
    }

    public class ResponseWrapper{
        @AuraEnabled 
        public integer statusCode {get; set;}
        @AuraEnabled 
        public String responseBody {get; set;}
        @AuraEnabled 
        public String statusInformation {get; set;}
        @AuraEnabled 
        public String status {get; set;}
        @AuraEnabled 
        public Decimal timeElapsed {get; set;}

        public ResponseWrapper(Httpresponse response){
            this.statusCode = response.getStatusCode();
            this.responseBody = response.getbody();
            this.statusInformation = response.toString();
            this.status = response.getStatus();
            this.timeElapsed = OutBoundIntegration.timeElapsed;
        }

        public ResponseWrapper(){
        }
    }

    //Holds information about the saved request for logging
    public class SavedRequestWrapper{
        @AuraEnabled 
        public String requestName {get; set;}
        @AuraEnabled 
        public String requestId {get; set;}
        @AuraEnabled 
        public String transactionOrigin {get; set;}
    }


    public class RequestResponseWrapper{
          
        public RestRequestController.RequestInformationWrapper reqInfoWrapper {get; set;}
        
        public RestRequestController.ResponseWrapper resWrapper {get; set;}
        
        public RestRequestController.SavedRequestWrapper saReqWrapper {get; set;}
        
        public RequestResponseWrapper(RestRequestController.RequestInformationWrapper reqInfoWrapper
        ,RestRequestController.ResponseWrapper resWrapper
        ,RestRequestController.SavedRequestWrapper saReqWrapper){
            this.reqInfoWrapper = reqInfoWrapper;
            this.resWrapper = resWrapper;
            this.saReqWrapper = saReqWrapper;
        }
    }
    

}